### ISSUE TITLE
Toggle to prevent screenshots

### ISSUE THREAD

**Issue by jcperil** [jmiskovic/hextrument#17]
_Swipe three fingers to take a screenshot_ is a feature on my phone that is very useful to me. So, I keep it enabled all the time. However, as you can imagine, when my cousin (2 yr old) plays the game, she often ends up taking screenshots of the screen.

Can you please add a toggle in the settings so that we can disable screenshots inside the app? Thank you.

<p align=center><img src="https://github.com/nicolasbrailo/PianOli/assets/89805719/5567582b-09ec-4f6e-8afb-bbd4dddb2e65"/></p>

**Comment by jmiskovic** [comment]
The feature you bring up is specific to phone manufacturer. App developers can't really prevent screenshoting even on stock Android, let alone with features added by different vendors. Sorry.
