### ISSUE TITLE
Exit on start

### ISSUE THREAD

**Issue by jmiskovic** [jmiskovic/hextrument#4]
App exits immediately after launching, without any error message.

A logcat would help to investigate this further.

Version name
    0.28.0 
Devices
    10 Viking Pro (RCT6303W87M7)
     Galaxy J1 (j13g)
    8050E (Pixi4-6_3G)
    V30 (joan)
    P9 lite (HWVNS-H)

**Comment by jmiskovic** [comment]
Can anyone with this issue try installing and running the [LÖVE for Android](https://play.google.com/store/apps/details?id=org.love2d.android) app? 

If LÖVE app starts correctly, we can get Hexpress running on same phone.

**Comment by PurpleCodingWizard** [comment]
That love app is working correctly but hexpress is not(exits after start)

**Comment by jmiskovic** [comment]
Thanks for checking that. In that case, you can use the special compatibility release I've just created. 

**Edit:** Unfortunately, the workaround below won't work. I just saw that LÖVE for Android app on Play store is still at version v0.10, while Hexpress uses v11. Hopefully they will update LÖVE on Play store to newest version, until then I'll try to think of something else.

> You would need to download compatibility release and extract content to _/sdcard/_ directory on phone (this is where Download, Music, Videos directories are located). Make sure that /sdcard/lovegame/main.lua exists to ensure that the files are in right place. After that, just run **LÖVE for Android app** and it should work.

**Comment by PurpleCodingWizard** [comment]
![screenshot_2019-01-30-09-32-07](https://user-images.githubusercontent.com/34276732/51957560-11694b00-2444-11e9-98c9-26a03dc8cdb4.png)

The love app was last updated in 2016, it's 2019 , an update may not happen.

**Comment by jmiskovic** [comment]
The Love framework has switched to v11 few months ago, and they target many platforms. The Love android platform is also switching to v11, it's already stable and any developer can already build new version. I have no idea when they plan to release it.

I can share with you my [android build of Love v11](https://www.dropbox.com/s/d2k6r87n82fxk72/love2d-v11-android.apk?dl=0) if you want to try the above workaround. Of course, this is very clumsy workaround and the APK might fail to start for you :( But if it succeeds, it will give me more information on how to fix the official app.

**Comment by PurpleCodingWizard** [comment]
I tried the one you shared and even the one from this website https://love2d.org/ (v11.1) Unfortunately both exit after start :(

**Comment by jmiskovic** [comment]
I neglected to mention this was fixed with release 0.29.

The bug was caused by power-saving feature of app: When the app was pushed to background, it would actually close itself. The startup time is negligible. Unfortunately, on some devices the startup would cause this logic to trigger and the app would automatically close itself. I managed to get such device and fix the issue.
