### ISSUE TITLE
Hex instrument crashes 

### ISSUE THREAD

**Issue by Dave195423** [jmiskovic/hextrument#5]
Error

patches/analog/analog.lua:75: attempt to perform arithmetic on field 'volume' (a nil value)

Traceback

patches/analog/analog.lua:75: in function 'drawCell'
hexpad.lua:97: in function 'draw'
patches/analog/analog.lua:118: in function 'draw'
main.lua:86: in function 'actualLoveDraw'
toolset.lua:18: in function 'draw'
[C]: in function 'xpcall'

**Comment by jmiskovic** [comment]
Thanks for reporting this. I was able to reproduce and fix the bug. Please update to newest release.

The root cause was the inconvenient timing of touch event. The touch data was accessed for visualization purposes before the data was injected with associated volume information.

**Comment by Dave195423** [comment]
Thanks!
