### ISSUE TITLE
Did v37 change the packageName?

### ISSUE THREAD

**Issue by IzzySoft** [jmiskovic/hextrument#9]
The APK attached to the latest release no longer identifies as `com.castlewrath.hexpress` but as `com.castlewrath.hexpress.embed`. Was that intended? That makes updating from a previous version impossible.

**Comment by jmiskovic** [comment]
Thanks for letting me know. The Love2d Android build system changed and I still have to learn its quirks.

I've just replaced the APK in the release v37 with corrected package name. I hope this won't create confusion.

**Comment by IzzySoft** [comment]
Thanks, confirmed – and updates re-enabled in my repo. In case you want to [link to it](https://apt.izzysoft.de/fdroid/index/apk/com.castlewrath.hexpress) from your Readme (any [F-Droid](https://f-droid.org/) client can be used to install and keep it updated on-device), I can even [offer a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) for that :smiley:
